env:
  DISTRIBUTION: zulu
  GRADLE_COMMAND: ./gradlew --no-daemon
  JDK: '17'
jobs:
  benchmark:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JDK }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.DISTRIBUTION }}
        java-version: ${{ env.JDK }}
    - continue-on-error: true
      name: JMH
      run: ${{ env.GRADLE_COMMAND }} clean :zuul-core:jmh
name: benchmark
on:
  repository_dispatch:
    types: trigger-ga___benchmark.yml
permissions:
  contents: read
