jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Git
      run: 'git config --global user.name ''Zuul Build''

        git config --global user.email ''zuul-build@netflix.com''

        '
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
        NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
        NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
        NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
      name: Build snapshot
      run: ./gradlew build snapshot
name: Snapshot
on:
  repository_dispatch:
    types: trigger-ga___snapshot.yml
